# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'right_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

"""
注意 手动进行了修改  不是right_window.ui中的样子了
"""

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        # Form.resize(203, 343)
        self.widget = QtWidgets.QWidget(Form)
        # self.widget.setGeometry(QtCore.QRect(0, 0, 197, 94))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.go_back_history_button = QtWidgets.QPushButton(self.widget)
        self.go_back_history_button.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.go_back_history_button)
        self.start_button = QtWidgets.QPushButton(self.widget)
        self.start_button.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.time_edit = QtWidgets.QLineEdit(self.widget)
        self.time_edit.setObjectName("lineEdit")
        self.who_turn_edit = QtWidgets.QLineEdit(self.widget)
        self.who_turn_edit.setObjectName("lineEdit_2")
        # 先显示轮到谁走了，再显示计时
        self.verticalLayout.addWidget(self.who_turn_edit)
        self.verticalLayout.addWidget(self.time_edit)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.go_back_history_button.setText(_translate("Form", "悔棋"))
        self.start_button.setText(_translate("Form", "开始"))
        self.time_edit.setText(_translate("Form", "计时:   "))
        self.who_turn_edit.setText(_translate("Form", ""))
