# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'right_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        # Form.resize(203, 343)
        self.widget = QtWidgets.QWidget(Form)
        # self.widget.setGeometry(QtCore.QRect(0, 0, 197, 94))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.go_back_history_button = QtWidgets.QPushButton(self.widget)
        self.go_back_history_button.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.go_back_history_button)
        self.start_button = QtWidgets.QPushButton(self.widget)
        self.start_button.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.start_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.go_back_history_button.setText(_translate("Form", "悔棋"))
        self.start_button.setText(_translate("Form", "开始"))
        self.lineEdit.setText(_translate("Form", "黑方计时:   "))
        self.lineEdit_2.setText(_translate("Form", "红方计时:   "))
